const About = () => {
  return (
    <div className="about-container">

      <h1>About This Application</h1>

      <section className="warning">
        <h2>API Usage Notice</h2>
        <p>
          This application uses the <strong>Gemini 2.5 Flash</strong> model on
          the free tier. The free tier has strict rate limits and usage quotas.
        </p>

        <ul>
          <li>RPM — Requests Per Minute limit</li>
          <li>RPD — Requests Per Day limit</li>
          <li>TPM — Tokens Per Minute limit</li>
        </ul>

        <p>
          Excessive or abusive usage may cause the API to temporarily reject
          requests. Please use the service responsibly.
        </p>
      </section>

      <section>
        <h2>What is this App?</h2>
        <p>
          Code Explainer is an AI-powered developer tool designed to help
          programmers understand unfamiliar code quickly. Instead of manually
          analyzing complex logic, users can paste their code and receive a
          clear explanation generated by an AI model.
        </p>
        <p>
          The application is intended for students, beginners, and developers
          who want to learn how code works without spending excessive time
          reading documentation or reverse-engineering logic.
        </p>
      </section>

      <section>
        <h2>What Does It Do?</h2>
        <ul>
          <li>Accepts source code input from the user.</li>
          <li>Sends the code to an AI model for analysis.</li>
          <li>Generates a natural language explanation.</li>
          <li>Displays the explanation in a readable format.</li>
          <li>Helps developers understand logic, structure, and intent.</li>
        </ul>
      </section>

      <section>
        <h2>Workflow</h2>
        <ol>
          <li>User pastes code into the editor.</li>
          <li>User clicks <strong>"Explain Code"</strong>.</li>
          <li>The frontend sends a request to the backend API.</li>
          <li>The backend forwards the code to the Gemini AI model.</li>
          <li>The AI generates a structured explanation.</li>
          <li>The explanation is returned and displayed in the UI.</li>
        </ol>
      </section>

      <section>
        <h2>How It Works ?</h2>

        <h4>Frontend</h4>
        <p>
          The frontend is built with React. It provides the code editor,
          interaction controls, and the explanation panel. The UI captures user
          input and sends it to the backend using an HTTP request.
        </p>

        <h4>Backend</h4>
        <p>
          The backend is build with Django and Django REST framework, which acts as a secure bridge between the frontend and the
          Gemini API. It receives the code from the client, constructs the AI
          prompt, and sends the request to Google's Gemini model. The generated
          response is then returned to the frontend for display.
        </p>
      </section>

      <br></br>
      <h1>Thank You !</h1>

    </div>
  );
};

export default About;